// Placeholder pixel art. Each sprite is a grid of letters; each letter is a
// colour from PALETTE and '.' is see-through. Edit a row, save, and the game
// reloads with the change. Every art pixel is drawn as PX × PX world pixels.
export const PX = 4

export const PALETTE = {
  // Ozo
  k: '#10202c', d: '#1b3346', b: '#2b5470', B: '#40789a', w: '#fff4cf', e: '#ffffff',
  y: '#ffd23f', o: '#ff8a33', r: '#ef4f6a', l: '#f59a3a', g: '#7f97a8', G: '#2c3e4c', m: '#8ff7d2',
  // Enemies
  n: '#4fc47e', N: '#2d8a58', h: '#a8f0b8', t: '#ffffff',
  p: '#b07cd8', P: '#7648a0', q: '#e0b8f5', s: '#ff7fb8', S: '#ffd0e6',
  // Loot and effects
  c: '#ffd23f', C: '#d9932a', u: '#fff7b0', a: '#7ef2df', A: '#2fb3a0', z: '#d8fff7',
  H: '#ff5a7a', R: '#c63a5c', i: '#ffc2cf',
  // Level
  v: '#78d04e', V: '#4a9e3a', x: '#c27a4a', X: '#98583a', j: '#e3a468',
  f: '#c08850', F: '#8a5a32', T: '#e6d2ae', E: '#b59c76', D: '#6e5842',
  W: '#ffffff',
  // Background jungle
  O: '#93cfa6', Q: '#7dbf96', I: '#b0dfbd', J: '#6fb98f', K: '#579f7a', L: '#4a8a6a',
  // Background critters: birds and tree monkeys
  M: '#9a6035',
  // Finlay's bosses (digits, as the letters are all used)
  0: '#4a2c6e', // Ring Star's outline
  1: '#3b2f86', 2: '#5a4ac0', 3: '#231a52', // Prince Nova's shell, highlight, seam
  4: '#f3cfa6', 5: '#d8a97c', // skin, skin shadow
  6: '#eef0f6', 7: '#b8bccb', // Ring Star's fur, fur shadow
  8: '#d23a3a', 9: '#8e2323', // Rap Bandit's hoodie, hoodie shadow
}

// Ozo faces right. Rows 0–13 are the body; the last rows are the legs.
// Six blank columns are added on the left (see `legs`) so his body sits in the
// middle of the image: flipping to face left mirrors around the middle.
const OZO_TOP = [
  '....ddd.........',
  '...dbbBd........',
  '..dbbbbBd.......',
  '..dbbweedyyyyy..',
  '..dbwekedyyyyyy.',
  '..dbwwwwdyyyyyyr',
  '..dbbwwwoooooorr',
  '..dbbbwwd.......',
  '.ddbbbwww...G...',
  'ddbbbbwGGGGGGGG.',
  'dbbbbbwGgggggggm',
  '.ddbbbbGgGGGGGG.',
  '..ddbbbGgG......',
  '...ddddGG.......',
]
const legs = rows => [...OZO_TOP, ...rows].map(row => '......' + row)

export const SPRITES = {
  'ozo-idle': legs([
    '....l..l........',
    '....l..l........',
    '....ll.ll.......',
    '................',
  ]),
  'ozo-jump': legs([
    '...ll.ll........',
    '...l..l.........',
    '................',
    '................',
  ]),
  'ozo-run-0': legs([
    '....l...l.......',
    '...l....l.......',
    '..ll....ll......',
    '................',
  ]),
  'ozo-run-1': legs([
    '....l..l........',
    '....l.l.........',
    '....llll........',
    '................',
  ]),
  'ozo-run-2': legs([
    '....l...l.......',
    '....l....l......',
    '....ll...ll.....',
    '................',
  ]),
  'ozo-run-3': legs([
    '.....l.l........',
    '.....ll.........',
    '....llll........',
    '................',
  ]),
  glider: [
    '......oooooo......',
    '...ooyyyyyyyyoo...',
    '.oyyyyyyyyyyyyyyo.',
    'oyyoyyyyooyyyyoyyo',
    'o...l........l...o',
  ],
  alert: [
    'yy',
    'yy',
    'yy',
    'yy',
    '..',
    'yy',
  ],

  snapper: [
    '....nnnnnn....',
    '...nhhnnnnnn..',
    '..nhnnnnnnnnn.',
    '..nnnnnnnnnnn.',
    '.nnneeknneeknn',
    '.nnneeknneeknn',
    '.nnnnnnnnnnnnn',
    'nnnnnnnnnnnnnn',
    'nnkkkkkkkkkkkn',
    'nnktktktktktkn',
    'nnkkkkkkkkkkkn',
    'nnktktktktktkn',
    '.nnnnnnnnnnnnN',
    '.NnnnnnnnnnnN.',
    '..NNNNNNNNNN..',
    '..NN......NN..',
  ],
  spitter: [
    '.....pppp.....',
    '....pqqppp....',
    '...pqpppppp...',
    '..ppppppppppp.',
    '..ppppppppppp.',
    '..ppeekppeekp.',
    '.pppeekppeekpp',
    '.pppppppppppss',
    'ppppppppppsSSs',
    'pppppppppppsss',
    'ppppppppppppp.',
    'ppppppppppppp.',
    '.ppppppppppppP',
    '.PpppppppppPP.',
    '..PPPPPPPPPP..',
    '..PP......PP..',
  ],
  'spitter-charge': [
    '.....pppp.....',
    '....pqqppp....',
    '...pqpppppp...',
    '..ppppppppppp.',
    '..ppppppppppp.',
    '..ppeekppeekp.',
    '.pppeekppeekpS',
    '.pppppppppsssS',
    'ppppppppppsSkS',
    'ppppppppppsssS',
    'ppppppppppppp.',
    'ppppppppppppp.',
    '.ppppppppppppP',
    '.PpppppppppPP.',
    '..PPPPPPPPPP..',
    '..PP......PP..',
  ],

  coin: [
    '..ccc..',
    '.cuccC.',
    'cucCccC',
    'cccCccC',
    'cccCccC',
    '.cccCC.',
    '..CCC..',
  ],
  research: [
    '..z..',
    '.zaa.',
    'zaaaA',
    'aaaAA',
    'aaAAA',
    '.aAA.',
    '..A..',
  ],
  pop: [
    '.mmmm.',
    'mmWWWm',
    '.mmmm.',
  ],
  // A quick bright flash at the end of the blaster when Ozo shoots.
  flash: [
    '..u..',
    '.uWu.',
    'uWWWu',
    '.uWu.',
    '..u..',
  ],
  // A Spiky's burr: fired three at a time in a spread.
  burr: [
    '.D.D.',
    'DXHXD',
    '.HHH.',
    'DXHXD',
    '.D.D.',
  ],
  'enemy-pop': [
    '.sss.',
    'sSSss',
    'sSsss',
    'sssss',
    '.sss.',
  ],
  heart: [
    '.HH.HH.',
    'HiHHHHR',
    'HHHHHHR',
    '.HHHHR.',
    '..HHR..',
    '...R...',
  ],
  px: ['W'],

  // Level tiles, repeated to fill each platform.
  grass: [
    'vvvVvvvv',
    'VvvvvVvv',
    'xVxxVxxV',
  ],
  dirt: [
    'xxxxxxxx',
    'xxjxxxxx',
    'xxxxxxXx',
    'xxxxxxxx',
    'xXxxxxxx',
    'xxxxxjxx',
    'xxxxxxxx',
    'xxxXxxxx',
  ],
  ledge: [
    'jjjjjjjj',
    'ffffffff',
    'fFffffFf',
    'ffffffff',
    'FFFFFFFF',
    'F......F',
  ],
  'stone-0': [
    'TTTTTTTTTTTT',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TEEEEEEEEEEE',
    'DDDDDDDDDDDD',
  ],
  'stone-1': [
    'TTTTTTTTTTTT',
    'TTTTTTTTTTTE',
    'TTTDTTTTTTTE',
    'TTTTDTTTTTTE',
    'TTTDTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTDTTE',
    'TTTTTTTDTTTE',
    'TTTTTTTTTTTE',
    'TEEEEEEEEEEE',
    'DDDDDDDDDDDD',
  ],
  'stone-2': [
    'TTTTTDTTTTTT',
    'TTTDTDTTTTTE',
    'TTTDTTDTTTTE',
    'TTTTDTTDTTTE',
    'TDTDTTTTDTTE',
    'TTDTTTTTDTTE',
    'TTTTTTTTDTTE',
    'TTTTDTTDTDTE',
    'TTTDTTDTTTTE',
    'TEEDEEEEEEEE',
    'DDDDDDDDDDDD',
  ],
  // Rainy Ridge's moving raft: a mossy plank, repeated along its width.
  raft: [
    'VvVvvVvV',
    'jjjjjjjj',
    'fFffffFf',
    'ffffffff',
    'FFFFFFFF',
    '.F....F.',
  ],
  // The key that opens Rainy Ridge's door.
  key: [
    '.yyy.........',
    'yuuyy........',
    'yu.uyyyyyyyyy',
    'yy.yyCCCCyCyC',
    '.yyyC....y.y.',
    '..CC.....C.C.',
  ],
  // The locked door: planks, two iron bands and a gold keyhole. It fills the
  // doorway at the bottom of a tree trunk too tall to jump over.
  door: [
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'GGGGGGGGGGGGGGGG',
    'GgGGGGGGGGGGGGgG',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFfyyyyyyfFffF',
    'FffFfyykkyyfFffF',
    'FffFfyykkyyfFffF',
    'FffFfyyykyyfFffF',
    'FffFfyyykyyfFffF',
    'FffFfyyyyyyfFffF',
    'FffFfCCCCCCfFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'GGGGGGGGGGGGGGGG',
    'GgGGGGGGGGGGGGgG',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
    'FffFffFffFffFffF',
  ],
  // Tree-trunk bark around the door, repeated up to the sky.
  bark: [
    'DFDDDXDDDFDDDXDD',
    'DFDDDXDDDFDDDXDD',
    'DFDDXXDDDFDDXXDD',
    'DDFDXDDDDDFDXDDD',
    'DDFDXDDDDDFDXDDD',
    'DDFDDXDDDDFDDXDD',
    'DFDDDXDDDFDDDXDD',
    'DFDDDXDDDFDDDXDD',
  ],
  // Checkpoint flag: grey and low until Ozo reaches it, then raised.
  'flag-down': [
    '..G.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gGEEE......',
    '.gGEEEEEE...',
    '.gGEEEEEEEEE',
    '.gGEEEEEE...',
    '.gGEEE......',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    'DDDDD.......',
    'DDDDD.......',
  ],
  'flag-up': [
    '..G.........',
    '.gG.........',
    '.gGrrr......',
    '.gGrrrrrr...',
    '.gGrrrrrrrrr',
    '.gGrrrrrr...',
    '.gGrrr......',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    'DDDDD.......',
    'DDDDD.......',
  ],
  // The doorway is see-through: the dark inside is drawn behind it, so Ozo can go in.
  home: [
    '.........rr.........',
    '.......rrrrrr.......',
    '.....rrrrrrrrrr.....',
    '...rrrrrrrrrrrrrr...',
    '.rrrrrrrrrrrrrrrrrr.',
    'RRRRRRRRRRRRRRRRRRRR',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyy....yyyyyy..',
    '..yyyyy......yyyyy..',
    '..yyyyy......yyyyy..',
    '..yyyyy......yyyyy..',
    '..yyyyyy....yyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyyyffffyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..oooooooooooooooo..',
    '.........ff.........',
    '.........ff.........',
    '.........ff.........',
    '.........ff.........',
    '.........ff.........',
    '.......FFFFFF.......',
  ],
  // Background jungle. Kept pale and low-contrast so the gameplay stands out.
  // Far treeline, repeated along the level.
  'jungle-far': [
    '................................................................',
    '...........................I....................................',
    '........................IIIIIII.................................',
    '...........I...........IIIIOOOOI..............I.................',
    '........IIIIIII.......IIIOOOOOOOO..........IIIIIII..............',
    '.......IIIIOOOOI.....IIIOOOOOOOOOO........IIIIOOOOI.............',
    '..I...IIIOOOOOOOO....IIOOOOOOOOOOO...I...IIIOOOOOOOO...I........',
    'IIIIIIIIOOOOOOOOO....IIOOOOOOOOOOOIIIIIIIIIOOOOOOOOOIIIIIII....I',
    'IIOOOOIIOOOOOOOOO...OOOOOOOOOOOOOIIIIOOOOIIOOOOOOOOIIIIOOOOI..II',
    'OOOOOOOOOOOOOOOOQIIIIOOOOOOOOOOOIIIOOOOOOOOOOOOOOOIIIOOOOOOOOIII',
    'OOOOOOOOOOOOOOOQIIIIOOOOOOOOOOOOIIOOOOOOOOOOOOOOOOIIOOOOOOOOOIIO',
    'OOOOOOOOIOOOOOOQIIIOOOOOOOOOOOOQIIOOOOOOOOOOOOOOOOIIOOOOOOOOOIIO',
    'IOOOOIIIIIIIOOQQIIOOOOOOOOOOOOIIIIIIIOOOOOOOOOOIIIIIIIOOOOIIIIII',
    'OIOOIIIIOOOOIQQOOOOOOIOQOOOOQIIIIOOOOIOOOQQOOOIIIIOOOOIOOIIIIOOO',
    'OOOOIIIOOOOOOQQ.OOOIIIIIQQQQQIIIOOOOOOOOOQQQQQIIIOOOOOOOOIIIOOOO',
    'OOOOIIOOOOOOOOOOOOIIIOOOOOOQQIIOOOOOOOOOQQQOOOIIOOOOOOOOOIIOOOOO',
    'OQQOOOOOOOOOQQOOQOIIOOOOOOOOOOOOOOOOOQQQQQOOOOOOOOOOOOQQOOOOOOOO',
    'QQQQOOOOOOOQQOOOOOOOOOOOQQOOQOOOOOOOQQQQQQOOOOOOOOOOOQQQQOOOOOOO',
    'QQQOOOOOOOQQQOOOOQOOOOOQQOOOQOOOOOOQQQOOOQOOOOOOOOOOQQQQOOOOOOOQ',
    'QQOOQOOOOQQQQOOOOQOOOOQQQOOOQQOOOOQQQQOOOQOOOOQOOOOQQQQOOQOOOOQQ',
    'QOOOOQQQQQQQOOOOOQOQQQQQOOOOQOQQQQQQQOOOOQOOOOOQQQQQQQOOOOQQQQQQ',
    'OOOOOQOOQOOOOOOOOQOOOQOOOOOOQOOOOQOOOOOOOQOOOOOOOOQOQOOOOOOOQQOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
  ],
  'palm': [
    '............................',
    '............................',
    '............................',
    '............................',
    '.............J..............',
    '..........JJJJ.JJJ..........',
    '.........JJKJJJJKJJ.........',
    '.......JJKKJJyoJJKKJJ.......',
    '.......JKKJKKLyKKJKKJ.......',
    '......JKJJKK.LL.KKJJKJ......',
    '.....JJJJK....LK..KJJJJ.....',
    '....JJJJKK....LK..KKJJJJ....',
    '...JJKJK......LL....KJKJJ...',
    '..JJJJJK......LK....KJJJJJ..',
    '..JJJJ........LK......JJJJ..',
    '.J.K..........LL........K.J.',
    '.J............LK..........J.',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '..............LL............',
    '..............LK............',
    '..............LK............',
  ],
  'bush': [
    '..............................',
    '...............I..............',
    '............IIIIIII...........',
    '...........IIIIJJJJI..........',
    '.....III..IIIJJJJJJJJ..III....',
    '...IIIIIIIIIJJJJJJJJJIIIIIII..',
    '..IIIIJJJJJJJJJJJJJJIIIIJJJJJ.',
    '..IIJJJJJJJJJJJJJJJKIIJJJJJJJ.',
    '.JJJJJJJJJJJJJJJJJKJJJJJJJJJKK',
    '..KKKKKKKKKKKKKKKKKKKKKKKKKKK.',
    '..KKKKKKKKK.KKKKKKK.KKKKKKKKK.',
  ],
  'vine': [
    '...L...',
    '...L...',
    '...L...',
    '....L..',
    '....L..',
    '....L..',
    '....L.J',
    '....LJ.',
    '....LK.',
    '....L..',
    '....L..',
    '..J.L..',
    '...JL..',
    '...KL..',
    '...L...',
    '...L...',
    '...L.J.',
    '...LJ..',
    '..L.K..',
    '..L....',
    '..L....',
    'J.L....',
    '.JL....',
    '.KL....',
    '..L....',
    '..L....',
    '..L.J..',
    '..LJ...',
    '..LK...',
    '..L....',
    '...L...',
    '.J.L...',
    '..JL...',
    '..KL...',
    '..JJJ..',
    '.JJJJJ.',
  ],
  // Tiny background birds, two flap frames. A faint far-off silhouette.
  'bird-a': [
    '.G.G.',
    'G...G',
  ],
  'bird-b': [
    'G...G',
    '.GGG.',
  ],
  // A monkey hanging by one arm from a palm frond (the hand is the top-right
  // pixels), with ears, a pale face and a curly tail. It swings gently.
  monkey: [
    '.........DD.',
    '.........MD.',
    '.........MD.',
    '...MMMM..MD.',
    '..MMMMMM.MD.',
    '.TMTTTTMTMD.',
    '.MTkTTkTMMD.',
    '..MTTTTM.MD.',
    '...MTTM..MD.',
    '...MMMMMMMD.',
    '..MMTTTTMM..',
    '.MMMTTTTMM..',
    'M.MMTTTTMM..',
    'M..MMMMMM...',
    'M..MM..MM...',
    '.M.M....M...',
    '.MDD...DD...',
  ],

  // Finlay's enemy drawings, first met in Rainy Ridge. Same 4 px art pixels
  // as the Snapper and Spitter. Previews: art/finlay-enemies/.
  // Hatter: an egg on little boots, in a floppy swirly hat, with a round "O"
  // mouth. It hops towards Ozo.
  hatter: [
    '...rrrr.......',
    '..rryrrrr.....',
    '.rryyrrrrr....',
    '.rrrrrryrrr...',
    '.rryrrrrrrrr..',
    '.rrrrrrryrrrr.',
    '.RRRRRRRRRRRRr',
    '..ETTTTTTTTE..',
    '.ETTTTTTTTTTE.',
    '.ETeeeTTeeeTE.',
    '.ETekeTTekeTE.',
    '.ETeeeTTeeeTE.',
    '.ETTTTTTTTTTE.',
    '.ETTTkkTTTTTE.',
    '.ETTkRRkTTTTE.',
    '.ETTTkkTTTTTE.',
    '.ETTTTTTTTTTE.',
    '..ETTTTTTTTE..',
    '...EETTTTEE...',
    '.....EEEE.....',
    '.....F..F.....',
    '...FFF..FFF...',
  ],
  // Spiky: a round spiky ball with a crown of big spikes, little spikes round
  // the sides, big eyes, a flat mouth and skinny legs. It fires burrs, then
  // curls up (below) so shots bounce off.
  spiky: [
    '..........D.....',
    '.........DX.....',
    '......D..DXX....',
    '......DX.DXX....',
    '...D..DX.DXX..D.',
    '...DX.DXXDXXX.DX',
    '...DX.DXXDXXXDX.',
    '...DXDXXXDXXXX..',
    '...CllllllllC...',
    '..CllllllllllC..',
    'DXCleeelleeelCXD',
    '..ClekellekelC..',
    '..CleeelleeelC..',
    'DXCllllllllllCXD',
    '..ClllkkkklllC..',
    '...CllllllllC...',
    'DX..CCllllCC..XD',
    '.....CCCCCC.....',
    '......F..F......',
    '......F..F......',
    '.....FF..FFF....',
  ],
  // Spiky curled up: legs tucked, eyes shut, spikes all round. Same size as
  // 'spiky', so its collision box doesn't change.
  'spiky-curled': [
    '................',
    '................',
    '................',
    '..........D.....',
    '.........DX.....',
    '......D..DXX....',
    '......DX.DXX....',
    '...D..DX.DXX..D.',
    '...DX.DXXDXXX.DX',
    '...DX.DXXDXXXDX.',
    '...DXDXXXDXXXX..',
    '...CllllllllC...',
    'DXCllllllllllCXD',
    '..ClkkkllkkklC..',
    'DXCllllllllllCXD',
    '..CllllllllllC..',
    'DXCllllllllllCXD',
    '..DCllllllllCD..',
    '.DX.CCllllCC.XD.',
    '..D.DCCCCCCD.D..',
    '...D.D.DD.D.D...',
  ],

  // Finlay's bosses, not in any level yet. Previews: art/finlay-bosses/.
  // Prince Nova: a crown with an orb on top, a cross little face, and a round
  // shell split down the middle with a star badge and a swirl badge.
  'prince-nova': [
    '..........yy..........',
    '.........yuyy.........',
    '.........yyyy.........',
    '..........CC..........',
    '.....y....yy....y.....',
    '.....yy...yy...yy.....',
    '.....yyy.yyyy.yyy.....',
    '.....yHyyyaayyyHy.....',
    '.....CCCCCCCCCCCC.....',
    '.....544444444445.....',
    '....54k44444444k45....',
    '...5444kk4444kk4445...',
    '...544eee4444eee445...',
    '...544eke4444eke445...',
    '...5444444kk4444445...',
    '....54444k44k44445....',
    '.....555555555555.....',
    '...3211111331111113...',
    '..322111113311111113..',
    '.32211111133111111113.',
    '.321yyy11133111yyy113.',
    '.32yyCyy113311yCCyy13.',
    '.32yCCCy113311yCyCy13.',
    '.32yyCyy113311yyCCy13.',
    '.321yyy11133111yyy113.',
    '.32211111133111111113.',
    '..322111113311111113..',
    '...3331111331111333...',
    '.....33333yy33333.....',
  ],
  // Ring Star: horned helmet with a studded band and side flaps, a big grin,
  // a chest full of rings, huge fluffy fur arms and legs, and boots.
  'ring-star': [
    '.......T.........TTTT.........',
    '.......TT.......TT..TTE.......',
    '.......TTE......T....TE.......',
    '.......TTE...........TTE......',
    '.......TTTE..........TTE......',
    '........TTE..........TTE......',
    '........TTTE........TTTE......',
    '.........TTTE......TTTE.......',
    '.......GGGGGGGGGGGGGGGG.......',
    '.......GyGGyGGyGGyGGyGG.......',
    '......GG44444444444444GG......',
    '......GG44kk444444kk44GG......',
    '......GG4444k4444k4444GG......',
    '......GG44eee4444eee44GG......',
    '......GG44eke4444eke44GG......',
    '......GG44eee4444eee44GG......',
    '......GG44444444444444GG......',
    '......GG44k44444444k44GG......',
    '........444kkkkkkkk444........',
    '.........555555555555.........',
    '..........GGGGGGGGGG..........',
    '............000000............',
    '..7777...000kkkkkk000...7777..',
    '.766667.0pPPkykkykPPP0.766667.',
    '.7666660ppPPykyykyPPPP07666667',
    '.766660pppPPkCkkCkPPPPP066667.',
    '7666660pppPPkykkykPPPPP0666667',
    '.76660ppppPPykyykyPPPPPP066667',
    '.76660ppppPPkCkkCkPPPPPP06667.',
    '766660PPPPPPkykkykPPPPPP066667',
    '.76660PPPPPPykyykyPPPPPP066667',
    '.766660PPPPPkCkkCkPPPPP066667.',
    '7666660PPPPPkykkykPPPPP0666667',
    '.7666660PPPPykyykyPPPP07666667',
    '.766667.0PPPkCkkCkPPP0.766667.',
    '76666667.000kkkkkk000.76666667',
    '.7666667.766000000667..7666667',
    '.766667.7666G7..7G6667.766667.',
    '76666667.766G7..7G667.76666667',
    '.7666667.766G7..7G667..7666667',
    '.7.7.7.77666G7..7G6667.7.7.7.7',
    '........7666G7..7G6667........',
    '.........766G7..7G667.........',
    '.........766G7..7G667.........',
    '........7666G7..7G6667........',
    '........7666G7..7G6667........',
    '.........766G7..7G667.........',
    '........kWkkkk..kkkkWk........',
    '........GGGGGG..GGGGGG........',
  ],
  // Rap Bandit: angry eyes over a spotted blue bandit bandana (knot tail on
  // the left), a red hoodie with ribbed cuffs, gold headphones round the
  // neck, baggy jeans and big trainers.
  'rap-bandit': [
    '......555555......',
    '.....54444445.....',
    '....54k4444k45....',
    '....544k44k445....',
    '....54ee44ee45....',
    '....54ek44ke45....',
    '..bbbbbbbbbbbbbb..',
    '.BB.BWBBBBWBBB....',
    'BB..BBBWBBBBWB....',
    '.....BBWBBBBB.....',
    '......BBBBBB......',
    '.....99844899.....',
    '..98888kkkk88889..',
    '.989888kkkk888989.',
    '.989888yyyy888989.',
    '.989888ykky888989.',
    '.989888ykky888989.',
    '.98988CCkkCC88989.',
    '.98988CCkkCC88989.',
    '.989888kkkk888989.',
    '.989888kkkk888989.',
    '.989888kkkk888989.',
    '.989888kkkk888989.',
    '.989888kkkk888989.',
    '.9899999999999989.',
    '.989.bbbbbbbb.989.',
    '.999.bbbbbbbb.999.',
    '.999.bbbddbbb.999.',
    '.....bbd..dbb.....',
    '.....bbd..dbb.....',
    '.....bbd..dbb.....',
    '.....bbd..dbb.....',
    '.....bbd..dbb.....',
    '.....bbd..dbb.....',
    '....WWWW..WWWW....',
    '..WWWWWW..WWWWWW..',
    '..gggggg..gggggg..',
  ],
}

// Spiky about to fire: the same sprite with its spikes glowing red.
SPRITES['spiky-charge'] = SPRITES.spiky.map(row => row.replace(/X/g, 'H').replace(/D/g, 'R'))
