// Placeholder pixel art. Each sprite is a grid of letters; each letter is a
// colour from PALETTE and '.' is see-through. Edit a row, save, and the game
// reloads with the change. Every art pixel is drawn as PX × PX world pixels.
export const PX = 4

export const PALETTE = {
  // Ozo
  k: '#10202c', d: '#1b3346', b: '#2b5470', B: '#40789a', w: '#fff4cf', e: '#ffffff',
  y: '#ffd23f', o: '#ff8a33', r: '#ef4f6a', l: '#f59a3a', g: '#7f97a8', G: '#2c3e4c', m: '#8ff7d2',
  // Enemies
  n: '#4fc47e', N: '#2d8a58', h: '#a8f0b8', t: '#ffffff',
  p: '#b07cd8', P: '#7648a0', q: '#e0b8f5', s: '#ff7fb8', S: '#ffd0e6',
  // Loot and effects
  c: '#ffd23f', C: '#d9932a', u: '#fff7b0', a: '#7ef2df', A: '#2fb3a0', z: '#d8fff7',
  H: '#ff5a7a', R: '#c63a5c', i: '#ffc2cf',
  // Level
  v: '#78d04e', V: '#4a9e3a', x: '#c27a4a', X: '#98583a', j: '#e3a468',
  f: '#c08850', F: '#8a5a32', T: '#e6d2ae', E: '#b59c76', D: '#6e5842',
  W: '#ffffff',
  // Background jungle
  O: '#93cfa6', Q: '#7dbf96', I: '#b0dfbd', J: '#6fb98f', K: '#579f7a', L: '#4a8a6a',
  // Background critters: birds and tree monkeys
  M: '#9a6035',
}

// Ozo faces right. Rows 0–13 are the body; the last rows are the legs.
// Six blank columns are added on the left (see `legs`) so his body sits in the
// middle of the image: flipping to face left mirrors around the middle.
const OZO_TOP = [
  '....ddd.........',
  '...dbbBd........',
  '..dbbbbBd.......',
  '..dbbweedyyyyy..',
  '..dbwekedyyyyyy.',
  '..dbwwwwdyyyyyyr',
  '..dbbwwwoooooorr',
  '..dbbbwwd.......',
  '.ddbbbwww...G...',
  'ddbbbbwGGGGGGGG.',
  'dbbbbbwGgggggggm',
  '.ddbbbbGgGGGGGG.',
  '..ddbbbGgG......',
  '...ddddGG.......',
]
const legs = rows => [...OZO_TOP, ...rows].map(row => '......' + row)

export const SPRITES = {
  'ozo-idle': legs([
    '....l..l........',
    '....l..l........',
    '....ll.ll.......',
    '................',
  ]),
  'ozo-jump': legs([
    '...ll.ll........',
    '...l..l.........',
    '................',
    '................',
  ]),
  'ozo-run-0': legs([
    '....l...l.......',
    '...l....l.......',
    '..ll....ll......',
    '................',
  ]),
  'ozo-run-1': legs([
    '....l..l........',
    '....l.l.........',
    '....llll........',
    '................',
  ]),
  'ozo-run-2': legs([
    '....l...l.......',
    '....l....l......',
    '....ll...ll.....',
    '................',
  ]),
  'ozo-run-3': legs([
    '.....l.l........',
    '.....ll.........',
    '....llll........',
    '................',
  ]),
  glider: [
    '......oooooo......',
    '...ooyyyyyyyyoo...',
    '.oyyyyyyyyyyyyyyo.',
    'oyyoyyyyooyyyyoyyo',
    'o...l........l...o',
  ],
  alert: [
    'yy',
    'yy',
    'yy',
    'yy',
    '..',
    'yy',
  ],

  snapper: [
    '....nnnnnn....',
    '...nhhnnnnnn..',
    '..nhnnnnnnnnn.',
    '..nnnnnnnnnnn.',
    '.nnneeknneeknn',
    '.nnneeknneeknn',
    '.nnnnnnnnnnnnn',
    'nnnnnnnnnnnnnn',
    'nnkkkkkkkkkkkn',
    'nnktktktktktkn',
    'nnkkkkkkkkkkkn',
    'nnktktktktktkn',
    '.nnnnnnnnnnnnN',
    '.NnnnnnnnnnnN.',
    '..NNNNNNNNNN..',
    '..NN......NN..',
  ],
  spitter: [
    '.....pppp.....',
    '....pqqppp....',
    '...pqpppppp...',
    '..ppppppppppp.',
    '..ppppppppppp.',
    '..ppeekppeekp.',
    '.pppeekppeekpp',
    '.pppppppppppss',
    'ppppppppppsSSs',
    'pppppppppppsss',
    'ppppppppppppp.',
    'ppppppppppppp.',
    '.ppppppppppppP',
    '.PpppppppppPP.',
    '..PPPPPPPPPP..',
    '..PP......PP..',
  ],
  'spitter-charge': [
    '.....pppp.....',
    '....pqqppp....',
    '...pqpppppp...',
    '..ppppppppppp.',
    '..ppppppppppp.',
    '..ppeekppeekp.',
    '.pppeekppeekpS',
    '.pppppppppsssS',
    'ppppppppppsSkS',
    'ppppppppppsssS',
    'ppppppppppppp.',
    'ppppppppppppp.',
    '.ppppppppppppP',
    '.PpppppppppPP.',
    '..PPPPPPPPPP..',
    '..PP......PP..',
  ],

  coin: [
    '..ccc..',
    '.cuccC.',
    'cucCccC',
    'cccCccC',
    'cccCccC',
    '.cccCC.',
    '..CCC..',
  ],
  research: [
    '..z..',
    '.zaa.',
    'zaaaA',
    'aaaAA',
    'aaAAA',
    '.aAA.',
    '..A..',
  ],
  pop: [
    '.mmmm.',
    'mmWWWm',
    '.mmmm.',
  ],
  'enemy-pop': [
    '.sss.',
    'sSSss',
    'sSsss',
    'sssss',
    '.sss.',
  ],
  heart: [
    '.HH.HH.',
    'HiHHHHR',
    'HHHHHHR',
    '.HHHHR.',
    '..HHR..',
    '...R...',
  ],
  px: ['W'],

  // Level tiles, repeated to fill each platform.
  grass: [
    'vvvVvvvv',
    'VvvvvVvv',
    'xVxxVxxV',
  ],
  dirt: [
    'xxxxxxxx',
    'xxjxxxxx',
    'xxxxxxXx',
    'xxxxxxxx',
    'xXxxxxxx',
    'xxxxxjxx',
    'xxxxxxxx',
    'xxxXxxxx',
  ],
  ledge: [
    'jjjjjjjj',
    'ffffffff',
    'fFffffFf',
    'ffffffff',
    'FFFFFFFF',
    'F......F',
  ],
  'stone-0': [
    'TTTTTTTTTTTT',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTTTTE',
    'TEEEEEEEEEEE',
    'DDDDDDDDDDDD',
  ],
  'stone-1': [
    'TTTTTTTTTTTT',
    'TTTTTTTTTTTE',
    'TTTDTTTTTTTE',
    'TTTTDTTTTTTE',
    'TTTDTTTTTTTE',
    'TTTTTTTTTTTE',
    'TTTTTTTTDTTE',
    'TTTTTTTDTTTE',
    'TTTTTTTTTTTE',
    'TEEEEEEEEEEE',
    'DDDDDDDDDDDD',
  ],
  'stone-2': [
    'TTTTTDTTTTTT',
    'TTTDTDTTTTTE',
    'TTTDTTDTTTTE',
    'TTTTDTTDTTTE',
    'TDTDTTTTDTTE',
    'TTDTTTTTDTTE',
    'TTTTTTTTDTTE',
    'TTTTDTTDTDTE',
    'TTTDTTDTTTTE',
    'TEEDEEEEEEEE',
    'DDDDDDDDDDDD',
  ],
  // Checkpoint flag: grey and low until Ozo reaches it, then raised.
  'flag-down': [
    '..G.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gGEEE......',
    '.gGEEEEEE...',
    '.gGEEEEEEEEE',
    '.gGEEEEEE...',
    '.gGEEE......',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    'DDDDD.......',
    'DDDDD.......',
  ],
  'flag-up': [
    '..G.........',
    '.gG.........',
    '.gGrrr......',
    '.gGrrrrrr...',
    '.gGrrrrrrrrr',
    '.gGrrrrrr...',
    '.gGrrr......',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    '.gG.........',
    'DDDDD.......',
    'DDDDD.......',
  ],
  // The doorway is see-through: the dark inside is drawn behind it, so Ozo can go in.
  home: [
    '.........rr.........',
    '.......rrrrrr.......',
    '.....rrrrrrrrrr.....',
    '...rrrrrrrrrrrrrr...',
    '.rrrrrrrrrrrrrrrrrr.',
    'RRRRRRRRRRRRRRRRRRRR',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyy....yyyyyy..',
    '..yyyyy......yyyyy..',
    '..yyyyy......yyyyy..',
    '..yyyyy......yyyyy..',
    '..yyyyyy....yyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyyyffffyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..yyyyyyyyyyyyyyyy..',
    '..oooooooooooooooo..',
    '.........ff.........',
    '.........ff.........',
    '.........ff.........',
    '.........ff.........',
    '.........ff.........',
    '.......FFFFFF.......',
  ],
  // Background jungle. Kept pale and low-contrast so the gameplay stands out.
  // Far treeline, repeated along the level.
  'jungle-far': [
    '................................................................',
    '...........................I....................................',
    '........................IIIIIII.................................',
    '...........I...........IIIIOOOOI..............I.................',
    '........IIIIIII.......IIIOOOOOOOO..........IIIIIII..............',
    '.......IIIIOOOOI.....IIIOOOOOOOOOO........IIIIOOOOI.............',
    '..I...IIIOOOOOOOO....IIOOOOOOOOOOO...I...IIIOOOOOOOO...I........',
    'IIIIIIIIOOOOOOOOO....IIOOOOOOOOOOOIIIIIIIIIOOOOOOOOOIIIIIII....I',
    'IIOOOOIIOOOOOOOOO...OOOOOOOOOOOOOIIIIOOOOIIOOOOOOOOIIIIOOOOI..II',
    'OOOOOOOOOOOOOOOOQIIIIOOOOOOOOOOOIIIOOOOOOOOOOOOOOOIIIOOOOOOOOIII',
    'OOOOOOOOOOOOOOOQIIIIOOOOOOOOOOOOIIOOOOOOOOOOOOOOOOIIOOOOOOOOOIIO',
    'OOOOOOOOIOOOOOOQIIIOOOOOOOOOOOOQIIOOOOOOOOOOOOOOOOIIOOOOOOOOOIIO',
    'IOOOOIIIIIIIOOQQIIOOOOOOOOOOOOIIIIIIIOOOOOOOOOOIIIIIIIOOOOIIIIII',
    'OIOOIIIIOOOOIQQOOOOOOIOQOOOOQIIIIOOOOIOOOQQOOOIIIIOOOOIOOIIIIOOO',
    'OOOOIIIOOOOOOQQ.OOOIIIIIQQQQQIIIOOOOOOOOOQQQQQIIIOOOOOOOOIIIOOOO',
    'OOOOIIOOOOOOOOOOOOIIIOOOOOOQQIIOOOOOOOOOQQQOOOIIOOOOOOOOOIIOOOOO',
    'OQQOOOOOOOOOQQOOQOIIOOOOOOOOOOOOOOOOOQQQQQOOOOOOOOOOOOQQOOOOOOOO',
    'QQQQOOOOOOOQQOOOOOOOOOOOQQOOQOOOOOOOQQQQQQOOOOOOOOOOOQQQQOOOOOOO',
    'QQQOOOOOOOQQQOOOOQOOOOOQQOOOQOOOOOOQQQOOOQOOOOOOOOOOQQQQOOOOOOOQ',
    'QQOOQOOOOQQQQOOOOQOOOOQQQOOOQQOOOOQQQQOOOQOOOOQOOOOQQQQOOQOOOOQQ',
    'QOOOOQQQQQQQOOOOOQOQQQQQOOOOQOQQQQQQQOOOOQOOOOOQQQQQQQOOOOQQQQQQ',
    'OOOOOQOOQOOOOOOOOQOOOQOOOOOOQOOOOQOOOOOOOQOOOOOOOOQOQOOOOOOOQQOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'OOOOOQOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOOOOOOQOOOOOOOOOOQOOOOOOOQOOO',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
    'QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
  ],
  'palm': [
    '............................',
    '............................',
    '............................',
    '............................',
    '.............J..............',
    '..........JJJJ.JJJ..........',
    '.........JJKJJJJKJJ.........',
    '.......JJKKJJyoJJKKJJ.......',
    '.......JKKJKKLyKKJKKJ.......',
    '......JKJJKK.LL.KKJJKJ......',
    '.....JJJJK....LK..KJJJJ.....',
    '....JJJJKK....LK..KKJJJJ....',
    '...JJKJK......LL....KJKJJ...',
    '..JJJJJK......LK....KJJJJJ..',
    '..JJJJ........LK......JJJJ..',
    '.J.K..........LL........K.J.',
    '.J............LK..........J.',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '...............LL...........',
    '...............LK...........',
    '...............LK...........',
    '..............LL............',
    '..............LK............',
    '..............LK............',
  ],
  'bush': [
    '..............................',
    '...............I..............',
    '............IIIIIII...........',
    '...........IIIIJJJJI..........',
    '.....III..IIIJJJJJJJJ..III....',
    '...IIIIIIIIIJJJJJJJJJIIIIIII..',
    '..IIIIJJJJJJJJJJJJJJIIIIJJJJJ.',
    '..IIJJJJJJJJJJJJJJJKIIJJJJJJJ.',
    '.JJJJJJJJJJJJJJJJJKJJJJJJJJJKK',
    '..KKKKKKKKKKKKKKKKKKKKKKKKKKK.',
    '..KKKKKKKKK.KKKKKKK.KKKKKKKKK.',
  ],
  'vine': [
    '...L...',
    '...L...',
    '...L...',
    '....L..',
    '....L..',
    '....L..',
    '....L.J',
    '....LJ.',
    '....LK.',
    '....L..',
    '....L..',
    '..J.L..',
    '...JL..',
    '...KL..',
    '...L...',
    '...L...',
    '...L.J.',
    '...LJ..',
    '..L.K..',
    '..L....',
    '..L....',
    'J.L....',
    '.JL....',
    '.KL....',
    '..L....',
    '..L....',
    '..L.J..',
    '..LJ...',
    '..LK...',
    '..L....',
    '...L...',
    '.J.L...',
    '..JL...',
    '..KL...',
    '..JJJ..',
    '.JJJJJ.',
  ],
  // Tiny background birds, two flap frames. A faint far-off silhouette.
  'bird-a': [
    '.G.G.',
    'G...G',
  ],
  'bird-b': [
    'G...G',
    '.GGG.',
  ],
  // A monkey hanging by one arm from a palm frond (the hand is the top-right
  // pixels), with ears, a pale face and a curly tail. It swings gently.
  monkey: [
    '.........DD.',
    '.........MD.',
    '.........MD.',
    '...MMMM..MD.',
    '..MMMMMM.MD.',
    '.TMTTTTMTMD.',
    '.MTkTTkTMMD.',
    '..MTTTTM.MD.',
    '...MTTM..MD.',
    '...MMMMMMMD.',
    '..MMTTTTMM..',
    '.MMMTTTTMM..',
    'M.MMTTTTMM..',
    'M..MMMMMM...',
    'M..MM..MM...',
    '.M.M....M...',
    '.MDD...DD...',
  ],

  // Finlay's enemy drawings, not in any level yet. Same 4 px art pixels as
  // the Snapper and Spitter. Previews: art/finlay-enemies/.
  // An egg on little boots, in a floppy swirly hat, with a round "O" mouth.
  hatter: [
    '...rrrr.......',
    '..rryrrrr.....',
    '.rryyrrrrr....',
    '.rrrrrryrrr...',
    '.rryrrrrrrrr..',
    '.rrrrrrryrrrr.',
    '.RRRRRRRRRRRRr',
    '..ETTTTTTTTE..',
    '.ETTTTTTTTTTE.',
    '.ETeeeTTeeeTE.',
    '.ETekeTTekeTE.',
    '.ETeeeTTeeeTE.',
    '.ETTTTTTTTTTE.',
    '.ETTTkkTTTTTE.',
    '.ETTkRRkTTTTE.',
    '.ETTTkkTTTTTE.',
    '.ETTTTTTTTTTE.',
    '..ETTTTTTTTE..',
    '...EETTTTEE...',
    '.....EEEE.....',
    '.....F..F.....',
    '...FFF..FFF...',
  ],
  // A round spiky ball: a crown of big spikes, little spikes round the sides,
  // big eyes, a flat mouth and skinny legs.
  spiky: [
    '..........D.....',
    '.........DX.....',
    '......D..DXX....',
    '......DX.DXX....',
    '...D..DX.DXX..D.',
    '...DX.DXXDXXX.DX',
    '...DX.DXXDXXXDX.',
    '...DXDXXXDXXXX..',
    '...CllllllllC...',
    '..CllllllllllC..',
    'DXCleeelleeelCXD',
    '..ClekellekelC..',
    '..CleeelleeelC..',
    'DXCllllllllllCXD',
    '..ClllkkkklllC..',
    '...CllllllllC...',
    'DX..CCllllCC..XD',
    '.....CCCCCC.....',
    '......F..F......',
    '......F..F......',
    '.....FF..FFF....',
  ],
}
